[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = "src"
title = "Loomio Help"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/loomio/loomio-docs/edit/main/en/{path}"
site-url = "/en/user_manual/"

[output.html.redirect]
"/user_manual/users/sign_in/index.html" = "/en/user_manual/overview/orientation.html"
"/user_manual/threads/index.html" = "/en/user_manual/discussions/index.html"
"/user_manual/threads/intro_to_threads/index.html" = "/en/user_manual/discussions/index.html"
"/user_manual/threads/starting_threads/index.html" = "/en/user_manual/discussions/starting_a_discussion/index.html"
"/user_manual/threads/notifying_people/index.html" = "/en/user_manual/discussions/notifying_people/index.html"
"/user_manual/threads/navigating_threads/index.html" = "/en/user_manual/discussions/using_discussions/index.html"
"/user_manual/threads/thread_admin/index.html" = "/en/user_manual/discussions/formatting/index.html"
"/user_manual/threads/thread_admin/tasks.html" = "/en/user_manual/discussions/tasks/index.html"
"/user_manual/threads/invite_only/index.html" = "/en/user_manual/discussions/direct_discussions/index.html"
"/user_manual/threads/examples/index.html" = "/en/user_manual/discussions/examples/index.html"
"/user_manual/threads/templates/index.html" = "/en/user_manual/discussions/templates/index.html"
"/user_manual/threads/engaging_with_threads/index.html" = "/en/user_manual/discussions/engaging_with_discussions/index.html"
"/user_manual/getting_started/index.html" = "/en/user_manual/overview/index.html"
"/user_manual/getting_started/orientation.html" = "/en/user_manual/overview/orientation.html"
"/user_manual/getting_started/write-a-comment.html"  = "/en/user_manual/overview/how-to-participate.html"
"/user_manual/groups/intro_to_groups/index.html" = "/en/user_manual/groups/index.html"
"/user_manual/getting_started/decisions/index.html" = "/en/user_manual/making_decisions/index.html"
"/guides/advice_process/index.html" = "/en/user_manual/making_decisions/advice_process.html"
"/guides/consent_process/index.html" = "/en/user_manual/making_decisions/consent_process.html"
"/guides/consensus_process/index.html" = "/en/user_manual/making_decisions/consensus_process.html"
"/user_manual/polls/decisions/index.html" = "/en/user_manual/making_decisions/simple_decision_process.html"
"/user_manual/groups/membership/index.html" = "/en/user_manual/groups/inviting-people/index.html"
"/user_manual/groups/membership/management.html" = "/en/user_manual/groups/member-management/index.html"
"/user_manual/groups/membership/index.html" = "/en/user_manual/groups/inviting_people/index.html"
"/user_manual/groups/membership/management.html" = "/en/user_manual/groups/member_management/index.html"
"/user_manual/groups/membership/delegated_voters.html" = "/en/user_manual/groups/delegated_voters/index.html"
# "privacy" = "/en/policy/privacy"
# key-concepts  -> overview
