[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = "src"
title = "Loomio Help"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/loomio/loomio-docs/edit/main/en/{path}"
site-url = "/en/user_manual/"

[output.html.redirect]
"/user_manual/threads/index.html" = "/user_manual/discussions/index.html"
"/user_manual/threads/intro_to_threads/index.html" = "/user_manual/discussions/index.html"
"/user_manual/threads/starting_threads/index.html" = "/user_manual/discussions/starting_a_discussion/index.html"
"/user_manual/threads/notifying_people/index.html" = "/user_manual/discussions/notifying_people/index.html"
"/user_manual/threads/navigating_threads/index.html" = "/user_manual/discussions/using_discussions/index.html"
"/user_manual/threads/thread_admin/index.html" = "/user_manual/discussions/formatting/index.html"
"/user_manual/threads/thread_admin/tasks.html" = "/user_manual/discussions/tasks/index.html"
"/user_manual/threads/invite_only/index.html" = "/user_manual/discussions/direct_discussions/index.html"
"/user_manual/threads/examples/index.html" = "/user_manual/discussions/examples/index.html"
"/user_manual/threads/templates/index.html" = "/user_manual/discussions/templates/index.html"
"/user_manual/threads/engaging_with_threads/index.html" = "/user_manual/discussions/engaging_with_discussions/index.html"
# "privacy" = "/en/policy/privacy"
# key-concepts  -> overview
